import Head from "next/head";
import { useTranslation } from "react-i18next";

import HomeComponent from "@/page-components/Home";
// import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { getServerTranslations } from "@/utils/getServerTranslations";

function Home() {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>Beneficiary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeComponent />
      </main>
      <div>
        <h1>{t("welcome")}</h1>
        <p>{t("hello")}</p>
      </div>
    </>
  );
}

export const getStaticProps = async (context) => {
  const { locale } = context;
  const i18nNamespaces = ["common", "home"]; // Assuming you have defined i18nNamespaces
  console.log("locale", locale);
  return {
    props: {
      ...(await getServerTranslations(locale, i18nNamespaces)),
    },
  };
};

export default Home;
